// Minimal topojson -> equirectangular SVG path, no dependencies.
import fs from "node:fs";
const topo = JSON.parse(fs.readFileSync("/tmp/claude-0/wa/package/land-110m.json", "utf8"));
const { scale, translate } = topo.transform;

function decodeArc(arc) {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => {
    x += dx; y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
}
const arcs = topo.arcs.map(decodeArc);
const arcFor = (i) => (i < 0 ? arcs[~i].slice().reverse() : arcs[i]);

// Equirectangular into a 1000x500 box (lon -180..180, lat 90..-90)
const W = 1000, H = 500;
const px = (lon) => ((lon + 180) / 360) * W;
const py = (lat) => ((90 - lat) / 180) * H;
const r2 = (n) => Math.round(n * 10) / 10;

function ring(indices) {
  const pts = [];
  for (const i of indices) {
    const a = arcFor(i);
    for (let k = pts.length ? 1 : 0; k < a.length; k++) pts.push(a[k]);
  }
  // drop near-duplicate points to shrink the path
  const out = [];
  let last = null;
  for (const [lon, lat] of pts) {
    const p = [r2(px(lon)), r2(py(lat))];
    if (!last || Math.abs(p[0] - last[0]) > 0.4 || Math.abs(p[1] - last[1]) > 0.4) { out.push(p); last = p; }
  }
  if (out.length < 4) return "";
  return "M" + out.map((p) => p[0] + " " + p[1]).join("L") + "Z";
}

const geo = topo.objects.land;
const polys = geo.type === "GeometryCollection" ? geo.geometries : [geo];
let d = "";
for (const g of polys) {
  const list = g.type === "Polygon" ? [g.arcs] : g.arcs;
  for (const poly of list) for (const r of poly) d += ring(r);
}
fs.writeFileSync("src/world.js",
  "/* Simplified world land outline (Natural Earth 110m via world-atlas, public domain).\n" +
  "   Equirectangular projection into a 1000x500 viewBox. Generated by scripts/world.mjs. */\n" +
  "export const WORLD_W = " + W + ";\nexport const WORLD_H = " + H + ";\n" +
  "export const WORLD_PATH = " + JSON.stringify(d) + ";\n");
console.log("path chars:", d.length);
